### ISSUE TITLE
Use system console for logging when Pluto is running Pluto via the Cargo plugin

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/portlet#143]
Result of https://github.com/vaadin/portlet-support/issues/24
See info : https://github.com/vaadin/portlet-support/issues/24#issuecomment-558015598

When pluto is executed using Cargo container plugin its logs should be shown in the console.

I don't know how this can be done for Win but it's doable for *nix (see https://github.com/vaadin/portlet-support/issues/24#issuecomment-558015598).

May be it has sense to make a separate profile ( active by default in integration tests) that copies the `setenv.sh` to the required directory. That will allow to run Pluto without Cargo with logs in the console.
And another profile (may be) which removes `setenv.sh` file to restore the default behavior (not active by default).

**Comment by pleku** [comment]
This will probably never be important enough to happen.
