### ISSUE TITLE
Errors from embedded Flow web components are not visible in the UI

### ISSUE THREAD

**Issue by pleku** [vaadin/portlet#156]
When exporting a Flow component as a web component and embedding it into a page and there is an error on the server side, there is nothing visible in the UI for this, it just fails and you don't have any idea what has happened.

There should be at least in development mode a clear indication (visible error dialog) in the UI that something has failed. For production mode it might not be desired to get this behavior (at least out-of-the-box), so maybe it should be configurable. It is another thing should the default be different between development and production mode.

**Comment by joheriks** [comment]
Components embedded in Vaadin Portlets currently show server-side exceptions in the browser, while for standard Vaadin and embedded components we assume that such exception are readily visible in IDE console.
