### ISSUE TITLE
Vaadin Portlet releases use Flow snapshots

### ISSUE THREAD

**Issue by mshabarov** [vaadin/portlet#198]
### Description of the bug
Vaadin Portlet release job has an issue adding Flow and CDI add-on snapshot versions instead those defined in the release job parameters.

#### Workaround:
Use Vaadin BOM and exclude Flow and CDI from vaadin-portlet:
```xml
            <dependency>
                <groupId>com.vaadin</groupId>
                <artifactId>vaadin-bom</artifactId>
                <version>${vaadin.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.vaadin</groupId>
                <artifactId>vaadin-portlet</artifactId>
                <version>${vaadin-portlet.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>com.vaadin</groupId>
                        <artifactId>flow-server</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>com.vaadin</groupId>
                        <artifactId>flow-client</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>com.vaadin</groupId>
                        <artifactId>vaadin-cdi</artifactId>
                    </exclusion>
                </exclusions>                
            </dependency>

```
### Minimal reproducible example
 See vaadin-portlet-parent pom https://maven.vaadin.com/vaadin-prereleases/com/vaadin/vaadin-portlet-parent/1.0.0.beta4/vaadin-portlet-parent-1.0.0.beta4.pom
### Expected and actual behavior
 No snapshot versions, but final.
### Versions:
    - Vaadin Portlet version 1.0.0.beta4 and older.

**Comment by mcollovati** [comment]
Job configuration updated; to be tested in next release.

**Comment by mcollovati** [comment]
Just realized that vaadin-portlet-cdi is not deployed on vaadin-prereleases repository during release. Will add it

**Comment by mshabarov** [comment]
Tested with vaadin-portlet 1.0.0.beta5.
