### ISSUE TITLE
Run integration tests in the Liferay container

### ISSUE THREAD

**Issue by mshabarov** [vaadin/portlet#204]
Liferay basic support has been merged to master, but the automated integration tests should be added still.

Here are a couple ideas to make it automated:
1. The Liferay uses tomcat 9 by default as a servlet container, so we can use the same approach for downloading and starting the container in tests: `cargo-maven2-plugin` and `maven-antrun-plugin`.
see this draft for more details: https://github.com/vaadin/portlet/tree/liferay-test
2. The test portlets can be added to the Liferay page via `LayoutLocalServiceUtil` api:
   - Create a portlet which uses `LayoutLocalServiceUtil` for adding a layout and test portlet to the page on startup
   - Deploy it to Liferay container
   - Here is a good article about it https://liferayiseasy.blogspot.com/2015/01/adding-page-change-layout-adding.html

**Comment by joheriks** [comment]
## Acceptance criteria

- There is an abstract superclass based on `https://github.com/vaadin/portlet/blob/master/vaadin-portlet-integration-tests/shared/src/main/java/com/vaadin/flow/portal/AbstractPlutoPortalTest.java` that is implemented by both `LiferayPortalTest` and `PlutoPortalTest` concrete classes. For PlutoPortalTest, use `LayoutLocalServiceUtil` for setting up the portlets needed by the tests.
- There is a new test module `vaadin-portlet-integration-tests/liferay` which runs all tests in `tests-generic` and `portlet30` against the Liferay container.

**Comment by mshabarov** [comment]
`generic-tests` and `portlet30` have been migrated and passed on Liferay, except the portlet hub tests checking state and mode changes (they are ignored temporarily). A separate ticket is created to track the issue https://github.com/vaadin/portlet/issues/214.

The remaining part now is "automation" and making tests reuse the codes as much as possible (abstract superclass):

- [ ] There is an abstract superclass based on https://github.com/vaadin/portlet/blob/master/vaadin-portlet-integration-tests/shared/src/main/java/com/vaadin/flow/portal/AbstractPortalTest.java that is implemented by both LiferayPortalTest and PlutoPortalTest concrete classes.
- [ ]  Cargo plugin doesn't start Liferay - OutOfMemory errors occurred.
- [ ] Portlet Deployer module requires to be deployed after all test portlets.
- [ ] Liferay property file contains path to Liferay home, we need a way to inject the path automatically.
