### ISSUE TITLE
Deploy portlet in Liferay CE 7.4.3.19-ce-ga19: java.lang.IllegalStateException: Unable to configure jsr356 at that stage. ServerContainer is null

### ISSUE THREAD

**Issue by icarrara** [vaadin/portlet#222]
I have deployed the base-starter-flow-portlet and addressbook-portlet-feature-liferay modules to Liferay Portal CE 7.4.3.19-ce-ga19.

The portlets are installed and working perfectly.

But when deploying any portlet you get the following error: "java.lang.IllegalStateException: Unable to configure jsr356 at that stage. ServerContainer is null"

However the deployment is successful.

- Server logs: attached
- Versions:
    - Vaadin Portlet version:  1.0.0
    - Portal (Liferay) version: CE 7.4.3.19-ce-ga19 
    - Java version: 1.8.0_261
 
![vaadin-portlet-static](https://user-images.githubusercontent.com/2285400/163585534-d7af5aa1-7259-44a2-b13c-f808b6b9edd5.JPG)
![portlet-starter](https://user-images.githubusercontent.com/2285400/163585553-f08d3ea9-0647-4125-a6ad-3630e7bd0f26.JPG)

-----------------------------------

[vaadin-portlet-static-Tomcat-LOG.TXT](https://github.com/vaadin/portlet/files/8496576/vaadin-portlet-static-Tomcat-LOG.TXT)

-------------------------------------

[portlet-starter-Tomcat-LOG.txt](https://github.com/vaadin/portlet/files/8496579/portlet-starter-Tomcat-LOG.txt)

**Comment by mcollovati** [comment]
Hi, thanks for reporting.
This is a known issue with Atmosphere; see vaadin/portlet#200 for more detail.
Closing as duplicate
