### ISSUE TITLE
Do I need a Pro License to help develop Vaadin Portlet?

### ISSUE THREAD

**Issue by icarrara** [vaadin/portlet#223]
I would like to contribute to the development of Vaadin Portlet.

I use Liferay Portal and am available to run the tests necessary to bring Vaadin Portlet to be compatible with Liferay Portal version 7.4 and later.

After the 14-day trial of Vaadin Pro do I have to purchase the license or will I only need to do it when I go to production?

**Comment by mshabarov** [comment]
Hi @icarrara, thank you for considering contribution to Vaadin Portlet.
Vaadin Portlet license is a development time license, so you need it when developing, not during deployment and/or production usage.
Vaadin Portlet currently released for Vaadin 14, and is being forward-ported for Vaadin 23. It was tested with Liferay 7.3 and 7.4.
Could you please describe what kind of changes you want to contribute? Is it a bug fix or a fundamentals we missed during development?

**Comment by icarrara** [comment]
Hi @mshabarov , thank you for your reply.
I used Liferay in my projects since 2004 and right now I was exploring the possibility to implement a new project using Vaadin Portlet. I just tested it with Liferay 7.4.
Mainly my contribution should be testing and bug reporting.

My question here is if I should buy a license to run the tests, contribute to the development of Vaadin Portlet and then find out if it is suitable for my new project.

Thank you in advance for your support.

**Comment by mshabarov** [comment]
You need a Pro license to run the tests (for Vaadin TestBench framework) and for contribution you also need a licence. Vaadin Portlet will be included into Prime license (once we include it into Vaadin 23). But I believe for testing and exploring purposes you can use a trial.

**Comment by mshabarov** [comment]
@icarrara I've sent you a message to the email from you GH profile. So we can have a quick chat and discuss your needs and project.
